BASE_URL = "https://www.nseindia.com"
BASE_URL_ARCHIVES = "https://archives.nseindia.com"
BASE_URL_NSE1 = "https://www1.nseindia.com"
API_CONTEXT = "/api"
JSON_CONTEXT = "/json"
CONTENT_CONTEXT = "/content"
EQUITY_STOCK_INDICES = "/equity-stockIndices"
EXTENSION_CSV = ".csv"
